sudo: required
language: go

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libx11-dev libxtst-dev libc-dev binutils

install:
  - make build
  - bash deploy.bash
  
script:
  - echo END
